language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=hko,tests -m tests.test_hko
  - coverage run --source=hko,tests -m tests.test_hko_without_internet
  - coverage combine --append
after_success:
  - coveralls
